export const POINTS = {
  CHECK_IN_PER_SUBJECT: 10,
  CHECK_IN_ALL_COMPLETE_BONUS: 10,
  CHECK_IN_STREAK_7_BONUS: 50,
  LEARN_NEW_CONTENT: 5,
  GAME_COMPLETION_MIN: 5,
  GAME_COMPLETION_MAX: 20,
} as const;
